### ISSUE TITLE
When will the next version release? Is there any road map avalibale?

### ISSUE THREAD

**Issue by yxdming** [FastCGI-Archives/fcgi2#18]
When will the next stable version release? Is there any road map avalibale?
@mcarbonneaux 
Thx

**Comment by mcarbonneaux** [comment]
I do not have evolution roadmap, I only do fix maintenance.

There are so many more advanced fastcgi project than this sdk to use fastcgi protocol.

And this project is an archive of the old fastcgi project.

But contribution are welcome.

**Comment by yxdming** [comment]
> I do not have evolution roadmap, I only do fix maintenance.
> 
> There are so many more advanced fastcgi project than this sdk to use fastcgi protocol.
> 
> And this project is an archive of the old fastcgi project.
> 
> But contribution are welcome.

Hi, @mcarbonneaux 
I got you meaning, i found that the last stable release 2.4.1 which was released on 30 Mar 2017. 
But the code was modified recently.
So, do you have any plan to release a new version in recently.
Thx.

**Comment by mcarbonneaux** [comment]
You need new tag that include this fix?

**Comment by tehnick** [comment]
@mcarbonneaux 
Could you wait a bit before making of new git tag?
I'll prepare a small PR with important fix.

**Comment by mcarbonneaux** [comment]
Lol to late I've done a new tag... I can remove? Or I while do new one after your fix...

**Comment by tehnick** [comment]
> Lol to late I've done a new tag...

My bad. Sorry for inconvenience.

> I can remove?

Yes, because very few time have passed.

Just something like:
```
git push origin :2.4.1.1
```

**Comment by mcarbonneaux** [comment]
I've merged your pr and incremented to 2.4.2 in release

**Comment by tehnick** [comment]
@mcarbonneaux Thanks a lot!

**Comment by yxdming** [comment]
@mcarbonneaux 
Thx a lot!
