### ISSUE TITLE
When compile fcgi2 in AIX, i got the error: ar: 0707-126 libfcgi_la-fcgiapp.o is not valid with the current object file mode.

### ISSUE THREAD

**Issue by yxdming** [FastCGI-Archives/fcgi2#21]
When compile fcgi2 in AIX, i got the error: ar: 0707-126 libfcgi_la-fcgiapp.o is not valid with the current object file mode. The total message as below:

-bash-4.1# g++ -v
Using built-in specs.
COLLECT_GCC=g++
Target: powerpc-ibm-aix6.1.0.0
Configured with: ../gcc-4.8.2/configure --with-as=/usr/bin/as --with-ld=/usr/bin/ld --enable-languages=c,c++,fortran --prefix=/opt/freeware --mandir=/opt/freeware/man --infodir=/opt/freeware/info --enable-version-specific-runtime-libs --disable-nls --enable-decimal-float=dpd --host=powerpc-ibm-aix6.1.0.0
Thread model: aix
gcc version 4.8.2 (GCC)

the error as below

libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
agent_make.sh[19]: ./configure: cannot execute
onfigure: WARNING: you should use --build, --host, --target
checking for a BSD-compatible install... ./install-sh -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether make sets $(MAKE)... yes
checking build system type... powerpc-ibm-aix6.1.0.0
checking host system type... powerpc-ibm-aix6.1.0.0
checking for style of include used by make... GNU
checking for gcc... xlC_r
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... no
checking whether xlC_r accepts -g... yes
checking for xlC_r option to accept ISO C89... none needed
checking dependency style of xlC_r... xlc
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for non-GNU ld... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 786432
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... no
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for ar... ar
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from xlC_r object... failed
checking how to run the C preprocessor... xlC_r -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking for xlC_r option to produce PIC...  -DPIC
checking if xlC_r PIC flag  -DPIC works... yes
checking if xlC_r static flag -bnso -bI:/lib/syscalls.exp works... no
checking if xlC_r supports -c -o file.o... yes
checking if xlC_r supports -c -o file.o... (cached) yes
checking whether the xlC_r linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... aix6.1.0.0 ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... no
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking for gcc... (cached) xlC_r
checking whether we are using the GNU C compiler... (cached) no
checking whether xlC_r accepts -g... (cached) yes
checking for xlC_r option to accept ISO C89... (cached) none needed
checking dependency style of xlC_r... (cached) xlc
checking how to run the C preprocessor... xlC_r -E
checking for a BSD-compatible install... ./install-sh -c
checking for g++... g++
checking whether we are using the GNU C++ compiler... no
checking whether g++ accepts -g... no
checking dependency style of g++... none
checking whether we are using the GNU C++ compiler... (cached) no
checking whether g++ accepts -g... (cached) no
checking dependency style of g++... (cached) none
checking how to run the C++ preprocessor... /lib/cpp
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
libtool.m4: error: problem compiling CXX test program
checking for g++ option to produce PIC...  -DPIC
checking if g++ PIC flag  -DPIC works... no
checking if g++ static flag -bnso -bI:/lib/syscalls.exp works... no
checking if g++ supports -c -o file.o... no
checking if g++ supports -c -o file.o... (cached) no
checking whether the g++ linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... aix6.1.0.0 ld.so
checking how to hardcode library paths into programs... immediate
checking whether g++ works... no
checking for gethostbyname in -lnsl... yes
checking for socket in -lsocket... no
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking for the pthreads library -lpthreads... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... -D_THREAD_SAFE
checking for cc_r... cc_r
checking for ssize_t... yes
checking for sun_len in sys/un.h... yes
checking for fpos_t in stdio.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking for unistd.h... (cached) yes
checking for a fileno() prototype in stdio.h... yes
checking whether cross-process locking is required by accept()... no
checking whether va_arg(arg, long double) crashes the compiler... no
checking for an ANSI C-conforming const... yes
checking for strerror... yes
checking for inline... inline
checking host system type... (cached) powerpc-ibm-aix6.1.0.0
checking for C compiler warning flags... unknown
configure: creating ./config.status
 /bin/sh ./config.status
config.status: creating Makefile
config.status: creating cgi-fcgi/Makefile
config.status: creating include/Makefile
config.status: creating libfcgi/Makefile
config.status: creating examples/Makefile
config.status: creating fcgi.pc
config.status: creating fcgi++.pc
config.status: creating fcgi_config.h
config.status: fcgi_config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
make  all-recursive
make[1]: Entering directory `/home/workspace/Package_RD_Agent_AIX6_V2R1C30/Agent/open_src/fcgi'
Making all in libfcgi
make[2]: Entering directory `/home/workspace/Package_RD_Agent_AIX6_V2R1C30/Agent/open_src/fcgi/libfcgi'
/bin/sh ../libtool --tag=CC   --mode=link xlC_r -D_THREAD_SAFE  -g -q64 -DSTDCXX_98_HEADERS -DAIX -DWSEC_COMPILE_CAC_OPENSSL -DWSEC_OPENSSL101 -DWSEC_LINUX -DKMC_MULTIPROCESSSEC_ERR_CODE_BASE=0 -no-undefined  -o libfcgi.la -rpath /home/workspace/Package_RD_Agent_AIX6_V2R1C30/Agent/open_src/fcgi/.fcgi/lib  libfcgi_la-fcgiapp.lo libfcgi_la-fcgi_stdo libfcgi_la-os_unix.lo  -lnsl 
libtool: link: ar cru .libs/libfcgi.a  libfcgi_la-fcgiapp.o libfcgi_la-fcgi_stdio.o libfcgi_la-os_unix.o
ar: 0707-126 libfcgi_la-fcgiapp.o is not valid with the current object file mode.
        Use the -X option to specify the desired object mode.
ar: 0707-126 libfcgi_la-fcgi_stdio.o is not valid with the current object file mode.
        Use the -X option to specify the desired object mode.
ar: 0707-126 libfcgi_la-os_unix.o is not valid with the current object file mode.
        Use the -X option to specify the desired object mode.
make[2]: *** [libfcgi.la] Error 3
make[2]: Leaving directory `/home/workspace/Package_RD_Agent_AIX6_V2R1C30/Agent/open_src/fcgi/libfcgi'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/workspace/Package_RD_Agent_AIX6_V2R1C30/Agent/open_src/fcgi'
make: *** [all] Error 2

Does anyone solve this issue.
Thanks.

**Comment by mcarbonneaux** [comment]
ooo aix !

i think your problem are more libtool problem with aix than fcgi problem ...
you've played with -X option as the message say ?

**Comment by 372979131** [comment]
hi ,I have same Problem,I have changed  -q64 to -X. In this case, ./autogen.sh command failed,

Begin to compile snmp.
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:12: installing `./config.guess'
configure.ac:12: installing `./config.sub'
configure.ac:8: installing `./install-sh'
configure.ac:8: installing `./missing'
cgi-fcgi/Makefile.am: installing `./depcomp'
configure: WARNING: you should use --build, --host, --target
checking for a BSD-compatible install... ./install-sh -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... nawk
checking whether make sets $(MAKE)... yes
checking build system type... powerpc-ibm-aix6.1.0.0
checking host system type... powerpc-ibm-aix6.1.0.0
checking for style of include used by make... GNU
checking for gcc... xlC_r
checking for C compiler default output file name... 
configure: error: in `/home/workspace/Package_RD_Agent_AIX6_V2R1C30/Agent/open_src/fcgi':
configure: error: C compiler cannot create executables
See `config.log' for more details.

there have any other Suggestions
ths ！

**Comment by 372979131** [comment]
Also,I make install fcgi in windows failed ,many resource code error, 
header file exclude or other reson?

---- Build started: Project: fcgi, Configuration: Release x64 ------
1>Build started 05-05-2019 16:21:45.
1>InitializeBuildStatus:
1>  Touching "x64\Release\fcgi.unsuccessfulbuild".
1>PreBuildEvent:
1>          1 file(s) copied.
1>ClCompile:
1>  fcgiapp.c
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(68): warning C4273: 'FCGX_ShutdownPending' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(617) : see previous definition of 'FCGX_ShutdownPending'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(102): warning C4273: 'FCGX_GetChar' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(370) : see previous definition of 'FCGX_GetChar'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(137): warning C4273: 'FCGX_GetStr' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(403) : see previous definition of 'FCGX_GetStr'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(194): warning C4273: 'FCGX_GetLine' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(422) : see previous definition of 'FCGX_GetLine'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(230): warning C4273: 'FCGX_UnGetChar' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(386) : see previous definition of 'FCGX_UnGetChar'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(259): warning C4273: 'FCGX_HasSeenEOF' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(443) : see previous definition of 'FCGX_HasSeenEOF'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(276): warning C4273: 'FCGX_PutChar' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(463) : see previous definition of 'FCGX_PutChar'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(304): warning C4273: 'FCGX_PutStr' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(480) : see previous definition of 'FCGX_PutStr'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(350): warning C4273: 'FCGX_PutS' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(495) : see previous definition of 'FCGX_PutS'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(369): warning C4273: 'FCGX_FPrintF' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(511) : see previous definition of 'FCGX_FPrintF'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(405): warning C4273: 'FCGX_VFPrintF' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(513) : see previous definition of 'FCGX_VFPrintF'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(908): warning C4273: 'FCGX_FFlush' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(532) : see previous definition of 'FCGX_FFlush'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(933): warning C4273: 'FCGX_FClose' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(558) : see previous definition of 'FCGX_FClose'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(984): warning C4273: 'FCGX_GetError' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(570) : see previous definition of 'FCGX_GetError'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(997): warning C4273: 'FCGX_ClearError' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(581) : see previous definition of 'FCGX_ClearError'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1124): warning C4273: 'FCGX_GetParam' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(350) : see previous definition of 'FCGX_GetParam'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1491): error C2143: syntax error : missing ';' before 'type'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1492): error C2065: 'tmpPtr' : undeclared identifier
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1492): warning C4047: '!=' : 'int' differs in levels of indirection from 'void *'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1493): error C2065: 'tmpPtr' : undeclared identifier
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1493): error C2100: illegal indirection
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1512): error C2275: 'FCGI_Header' : illegal use of this type as an expression
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fastcgi.h(32) : see declaration of 'FCGI_Header'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1512): error C2065: 'header' : undeclared identifier
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1513): error C2065: 'header' : undeclared identifier
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1513): error C2100: illegal indirection
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1514): error C2440: '=' : cannot convert from 'FCGI_Header' to 'int'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1518): error C2275: 'FCGI_UnknownTypeRecord' : illegal use of this type as an expression
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fastcgi.h(133) : see declaration of 'FCGI_UnknownTypeRecord'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1518): error C2065: 'utr' : undeclared identifier
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1519): error C2065: 'utr' : undeclared identifier
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1519): error C2223: left of '->header' must point to struct/union
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1522): error C2065: 'utr' : undeclared identifier
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1522): error C2223: left of '->body' must point to struct/union
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1846): warning C4273: 'FCGX_FreeStream' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(609) : see previous definition of 'FCGX_FreeStream'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1931): warning C4273: 'FCGX_CreateWriter' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(593) : see previous definition of 'FCGX_CreateWriter'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(1964): warning C4273: 'FCGX_IsCGI' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(129) : see previous definition of 'FCGX_IsCGI'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(2003): warning C4273: 'FCGX_Finish' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(295) : see previous definition of 'FCGX_Finish'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(2027): warning C4273: 'FCGX_Finish_r' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(229) : see previous definition of 'FCGX_Finish_r'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(2048): warning C4273: 'FCGX_Free' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(241) : see previous definition of 'FCGX_Free'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(2065): warning C4273: 'FCGX_OpenSocket' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(161) : see previous definition of 'FCGX_OpenSocket'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(2075): warning C4273: 'FCGX_InitRequest' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(176) : see previous definition of 'FCGX_InitRequest'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(2103): warning C4273: 'FCGX_Init' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(143) : see previous definition of 'FCGX_Init'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(2156): warning C4273: 'FCGX_Accept' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(270) : see previous definition of 'FCGX_Accept'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(2204): warning C4273: 'FCGX_Accept_r' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(208) : see previous definition of 'FCGX_Accept_r'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(2302): warning C4273: 'FCGX_StartFilterData' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(314) : see previous definition of 'FCGX_StartFilterData'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(2330): warning C4273: 'FCGX_SetExitStatus' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(329) : see previous definition of 'FCGX_SetExitStatus'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(2338): warning C4273: 'FCGX_Attach' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(624) : see previous definition of 'FCGX_Attach'
1>..\..\..\..\open_src\fcgi\libfcgi\fcgiapp.c(2346): warning C4273: 'FCGX_Detach' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgiapp.h(625) : see previous definition of 'FCGX_Detach'
1>  os_win32.c
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(237): warning C4133: 'function' : incompatible types - from 'unsigned long *' to 'PULONG_PTR'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(264): warning C4273: 'OS_ShutdownPending' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(124) : see previous definition of 'OS_ShutdownPending'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(310): warning C4273: 'OS_LibInit' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(103) : see previous definition of 'OS_LibInit'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(560): warning C4273: 'OS_LibShutdown' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(104) : see previous definition of 'OS_LibShutdown'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(682): warning C4273: 'OS_CreateLocalIpcFd' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(105) : see previous definition of 'OS_CreateLocalIpcFd'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(806): warning C4273: 'OS_FcgiConnect' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(106) : see previous definition of 'OS_FcgiConnect'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(932): warning C4273: 'OS_Read' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(107) : see previous definition of 'OS_Read'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(995): warning C4273: 'OS_Write' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(108) : see previous definition of 'OS_Write'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(1062): warning C4273: 'OS_SpawnChild' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(109) : see previous definition of 'OS_SpawnChild'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(1141): warning C4273: 'OS_AsyncReadStdin' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(110) : see previous definition of 'OS_AsyncReadStdin'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(1185): warning C4273: 'OS_AsyncRead' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(112) : see previous definition of 'OS_AsyncRead'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(1262): warning C4273: 'OS_AsyncWrite' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(114) : see previous definition of 'OS_AsyncWrite'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(1357): warning C4273: 'OS_Close' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(116) : see previous definition of 'OS_Close'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(1437): warning C4273: 'OS_CloseRead' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(117) : see previous definition of 'OS_CloseRead'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(1470): warning C4273: 'OS_DoIo' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(118) : see previous definition of 'OS_DoIo'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(1494): warning C4133: 'function' : incompatible types - from 'unsigned long *' to 'PULONG_PTR'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(1681): warning C4028: formal parameter 8 different from declaration
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(1728): warning C4273: 'OS_Accept' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(119) : see previous definition of 'OS_Accept'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(1798): warning C4273: 'OS_IpcClose' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(120) : see previous definition of 'OS_IpcClose'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(1851): warning C4273: 'OS_IsFcgi' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(121) : see previous definition of 'OS_IsFcgi'
1>..\..\..\..\open_src\fcgi\libfcgi\os_win32.c(1871): warning C4273: 'OS_SetFlags' : inconsistent dll linkage
1>          D:\workspace\Package_RD_Agent_Windows_V2R1C30\Agent\open_src\fcgi\include\fcgios.h(122) : see previous definition of 'OS_SetFlags'
1>  Generating Code...
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:00.71
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by tehnick** [comment]
> Also,I make install fcgi in windows failed ,many resource code error,

Which compiler do you use? And how you build a library?

**Comment by 372979131** [comment]
use command nmake -f Makefile.nt and windows compiler is VS2010

**Comment by tehnick** [comment]
> hi ,I have same Problem,I have changed -q64 to -X. In this case, ./autogen.sh command failed,

Please use Markdown syntax in your messages. Current appearance of configuration log is in unreadable state. It should look like this:
```
1
2
3
...
```

**Comment by tehnick** [comment]
> use command `nmake -f Makefile.nt` and windows compiler is VS2010

Unfortunately, I cannot suggest anything in this case, because I do not use MSVC during very long time. With MinGW this library is built and work fine. Probably `Makefile.nt` should be updated or Visual Studio GUI should be used for building of library properly.

**Comment by 372979131** [comment]
OK,I test AIX6 compile.
I delete CFLAGS -q64 option,I can success compil,but  libfcgi.a maybe a 32 bit library. 
Other link libfcgi.a library ,get a error :
tform/kmc/lib -ldl -lpthread -lrt -lKMC -lcrypto -lfcgi 
ld: 0711-738 ERROR: Input file /home/workspace/Package_RD_Agent_AIX6_V2R1C30/Agent//obj/common/ConfigXmlParse.o:
        XCOFF32 object files are not allowed in 64-bit mode.
make: *** [/home/workspace/Package_RD_Agent_AIX6_V2R1C30/Agent//bin/libcommon.so] Error 8

Does anyone solve this issue.
Ths!

**Comment by mcarbonneaux** [comment]
i've tried to use gcc in place on xlc ?

http://www.bullfreeware.com/search.php?package=gcc&version=aix6.1

in forcing CC environement variable to force use gcc & g++ in place of xlc ?
beceause in autoconf message it's try to use xlc...
