### ISSUE TITLE
When compile fcgi2 in HP and SunOS,I get Some error.

### ISSUE THREAD

**Issue by 372979131** [FastCGI-Archives/fcgi2#24]
1.HP-UX.
Compile opentions :
CPPC=aCC
        CC=aCC
        cc=cc
        CFLAGS="-g -w -AA +DD64 -D_REENTRANT -DHP_UX_IA -DHP_UX -mt $KMC_OPT"
        cFLAGS="-g -w +DD64 -D_REENTRANT -DHP_UX_IA -DHP_UX -mt"
        oFLAGS="-g +DD64 -ldl"
        OFLAGS="-g +DD64 -ldl -ldcekt"
        dFLAGS="-g +DD64 -b"
        DFLAGS="-g +DD64 -b -ldcekt"
I get errors info :
/bin/sh ../libtool --tag=CC   --mode=link aCC -Ae  -g -w -AA +DD64 -D_REENTRANT -DHP_UX_IA -DHP_UX -mt -DWSEC_COMPILE_CAC_OPENSSL -DWSEC_OPENSSL101 -DWSEC_LINUX -DKMC_MULTIPROCESS -DWSEC_ERR_CODE_BASE=0 +w1   -o cgi-fcgi  cgi-fcgi.o ../libfcgi/libfcgi.la -lnsl 
libtool: link: aCC -Ae -g -w -AA +DD64 -D_REENTRANT -DHP_UX_IA -DHP_UX -mt -DWSEC_COMPILE_CAC_OPENSSL -DWSEC_OPENSSL101 -DWSEC_LINUX -DKMC_MULTIPROCESS -DWSEC_ERR_CODE_BASE=0 +w1 -o cgi-fcgi cgi-fcgi.o  ../libfcgi/.libs/libfcgi.a -lnsl -mt
aCC: warning 967: Option -AA, -Ai, or -AP does not apply to ANSI C compilation, ignored.
ld: Unsatisfied symbol "_frexp" in file ../libfcgi/.libs/libfcgi.a[libfcgi_la-fcgiapp.o]
ld: Unsatisfied symbol "_mcount" in file ../libfcgi/.libs/libfcgi.a[libfcgi_la-fcgiapp.o]
2 errors.
Makefile:315: recipe for target 'cgi-fcgi' failed
make[2]: *** [cgi-fcgi] Error 1
make[2]: Leaving directory '/home/workspace/Package_RD_Agent_HP1131_V2R1C30/Agent/open_src/fcgi/cgi-fcgi'
Makefile:507: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/workspace/Package_RD_Agent_HP1131_V2R1C30/Agent/open_src/fcgi'
Makefile:392: recipe for target 'all' failed
make: *** [all] Error 2

@yxdming

**Comment by 372979131** [comment]
2、SunOS，
make options:
       CPPC=CC
        CC=cc
        #for sqlite and securec
        cc=cc
        CFLAGS="-xmemalign -m64 -DSTDCXX_98_HEADERS -D_REENTRANT -mt -g -xcode=pic32 -DSOLARIS $KMC_OPT"
        cFLAGS=$CFLAGS
        OFLAGS="-g -xmemalign -m64 -lsocket -lnsl -luuid"
        oFLAGS=${OFLAGS}
        DFLAGS="-g -xmemalign -m64 -shared -lsocket -lnsl -luuid"
        dFLAGS=${DFLAGS}
Error info:

/bin/bash ../libtool --tag=CXX   --mode=link g++  -g -O2 -rpath /export/home/workspace/Package_RD_Agent_Solaris_V2R1C30/Agent/open_src/fcgi/.fcgi/lib -no-undefined  -o libfcgi++.la   fcgio.lo libfcgi.la -lsocket -lnsl 
libtool: link: ar cru .libs/libfcgi++.a  fcgio.o
libtool: link: ranlib .libs/libfcgi++.a
libtool: link: ( cd ".libs" && rm -f "libfcgi++.la" && ln -s "../libfcgi++.la" "libfcgi++.la" )
make[2]: Leaving directory `/export/home/workspace/Package_RD_Agent_Solaris_V2R1C30/Agent/open_src/fcgi/libfcgi'
Making all in cgi-fcgi
make[2]: Entering directory `/export/home/workspace/Package_RD_Agent_Solaris_V2R1C30/Agent/open_src/fcgi/cgi-fcgi'
source='cgi-fcgi.c' object='cgi-fcgi.o' libtool=no \
DEPDIR=.deps depmode=none /bin/bash ../depcomp \
cc -DHAVE_CONFIG_H -I. -I..  -I../include   -xcode=pic32 -m64 -v -c cgi-fcgi.c
/bin/bash ../libtool --tag=CC   --mode=link cc  -xcode=pic32 -m64 -v   -o cgi-fcgi  cgi-fcgi.o ../libfcgi/libfcgi.la -lsocket -lnsl 
libtool: link: cc -xcode=pic32 -m64 -v -o cgi-fcgi cgi-fcgi.o  ../libfcgi/.libs/libfcgi.a -lsocket -lnsl
Undefined                       first referenced
 symbol                             in file
mcount                              ../libfcgi/.libs/libfcgi.a(libfcgi_la-fcgiapp.o)
ld: fatal: Symbol referencing errors. No output written to cgi-fcgi
make[2]: *** [cgi-fcgi] Error 2
make[2]: Leaving directory `/export/home/workspace/Package_RD_Agent_Solaris_V2R1C30/Agent/open_src/fcgi/cgi-fcgi'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/export/home/workspace/Package_RD_Agent_Solaris_V2R1C30/Agent/open_src/fcgi'
make: *** [all] Error 2
@mcarbonneaux 
do you hava any suggestion!
thx

**Comment by tehnick** [comment]
Where did you find these systems? Do you really use them now?

**Comment by 372979131** [comment]
yes, some spot may use thsi  HP and SunOS,SO I need update fcgi .

**Comment by 372979131** [comment]
my work is data protection,so i need support suse, redhat,HP SunOS ,Widonws,so i need to update fcgi in every one OS.

**Comment by 372979131** [comment]
@mcarbonneaux @tehnick
The mcount defined  in what library? when compiled in SunOS ,the mcount function can not be found ?

**Comment by mcarbonneaux** [comment]
suse, redhat are linux ... and use natively gnu tool chain... but HP-ux, solaris and aix are not very up to date in gnu tool chaine and i've many problem with unix api, many on this system are not friendly with linux api...
windows version are more tested than this old unix beceause gnu gcc toolchain are realy up to date... 
i not use any more this old unix system in my jobs...

mcount are not fcgi related... it's gnu gcc toolchaine related...
https://ftp.gnu.org/pub/old-gnu/Manuals/gprof-2.9.1/html_node/gprof_25.html 

i see you use os cc to compile... i think is very bad idea...
i think you MUST use "gnu gcc" in place of the os cc you while have more friendly compiling... 
without that on this type of unix you while have many compatiblity problem...

it's very hard to aid you on this system...
