### ISSUE TITLE
Windows Vs2010 compile fcgi2 error

### ISSUE THREAD

**Issue by 372979131** [FastCGI-Archives/fcgi2#25]
1、fcgiapp.c, need use C++ compile。
2、os_win32.c need c compile.

But，when other lib link fcgi.lib,I get some errors: 
function in fcgios.h can,t be found.  
I guss, may be compiled win32.c wthis C ,so can,t found  os_read .... funcion.
how can i fix this situation

8>Time Elapsed 00:00:00.78
10>     Creating library ..\..\..\..\bin\plugins\libexchange.lib and object ..\..\..\..\bin\plugins\libexchange.exp
10>fcgi.lib(fcgiapp.obj) : error LNK2001: unresolved external symbol __imp_OS_ShutdownPending
10>fcgi.lib(fcgiapp.obj) : error LNK2001: unresolved external symbol __imp_OS_Write
10>fcgi.lib(fcgiapp.obj) : error LNK2001: unresolved external symbol __imp_OS_Read
10>fcgi.lib(fcgiapp.obj) : error LNK2001: unresolved external symbol __imp_OS_IpcClose
10>fcgi.lib(fcgiapp.obj) : error LNK2001: unresolved external symbol __imp_OS_CreateLocalIpcFd
10>fcgi.lib(fcgiapp.obj) : error LNK2001: unresolved external symbol __imp_OS_LibInit
10>fcgi.lib(fcgiapp.obj) : error LNK2001: unresolved external symbol __imp_OS_IsFcgi
10>fcgi.lib(fcgiapp.obj) : error LNK2001: unresolved external symbol __imp_OS_Accept
10>..\..\..\..\bin\plugins\libexchange.dll : fatal error LNK1120: 8 unresolved externals

**Comment by 372979131** [comment]
if os_win32.c compile with C++, will build faild.
so i used C and C++ compiler in same project.

**Comment by mcarbonneaux** [comment]
what compile procedure you used ?
