### ISSUE TITLE
close flags -G ,when produce configure use by autoconf?

### ISSUE THREAD

**Issue by 372979131** [FastCGI-Archives/fcgi2#26]
Hello
    when,produce configue use by autoconf,when compile fcgi. I found configue have -G flag,This Maybe cause link error ,unsatisfied symbol _mcount  error.

How can i close -G flag when proudce configue,use the autoconf.

ths ~~~~

**Comment by 372979131** [comment]
@tehnick

**Comment by 372979131** [comment]
@mcarbonneaux

**Comment by mcarbonneaux** [comment]
they sound like https://github.com/FastCGI-Archives/fcgi2/issues/24 ...
_mcount is gnu gcc tool chain related...

you compile on linux ? or oldish unix ? you use gnu gcc to compile ?

**Comment by 372979131** [comment]
I compile on HP-UX HPUX80 B.11.31 OS and aCC 。

**Comment by 372979131** [comment]
I see the configure file，in HP os case， I  alleged where the flag -G add ,add how can i close the -G flag

**Comment by mcarbonneaux** [comment]
configue file is generated by installed autotool in your os... sometime old autotool can make many problem in compilation... try most recent autotool... and prefere gcc in place on hp-ux acc
