### ISSUE TITLE
How to run a fcgi based app as a standalone server?

### ISSUE THREAD

**Issue by enhering** [FastCGI-Archives/fcgi2#29]
Hi!

I've managed to compile a simple example from the FastCGI archives, but it runs, displays some HTML code and then exits.

I've been through all the documentation many times, but could not discover what is needed to run the code as a standalone server.

I also could not discover how to choose if the FastCGI app will be contacted via sockets or TCP. How is it done, please?

Thanks a lot for your kind attention.

Best regards,

Eduardo.

**Comment by tehnick** [comment]
Google about `spawn-fcgi` and its analogues.

**Comment by mcarbonneaux** [comment]
https://github.com/lighttpd/spawn-fcgi
