### ISSUE TITLE
FastCGI Developer's Kit and C++

### ISSUE THREAD

**Issue by PowerUser1234** [FastCGI-Archives/fcgi2#31]
To who it may concern,

I have learned that FastCGI has default C++ bindings, for g++ compiling.  I have also been going through 

[https://fastcgi-archives.github.io/FastCGI_Developers_Kit_FastCGI.html](https://fastcgi-archives.github.io/FastCGI_Developers_Kit_FastCGI.html)

 with some interest. Is it possible for someone to update this tutorial or include some more FastCGI C++ tutorial support including responses to the following:

-How do I install and configure FastCGI for Apache, if it isn't enables easily or already done so in Apache, by default?
-How do I write and compile a simple FastCGI C++ Program using g++?
-How do I write html, css, javascript to an .html web document?
-How do I read http GET and POST content to and from variables involved in GET and POST actions from an html (http) web form action?
-Can someone at least reply to my post here?

**Comment by mcarbonneaux** [comment]
***-How do I install and configure FastCGI for Apache, if it isn't enables easily or already done so in Apache, by default?***

Apache from 2.4 version  includes fastcgi support.

In the [front page](https://fastcgi-archives.github.io/ ) you have many link to using fastcgi with apache... The main link i think is this one : https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html 

is oriented with php fastcgi in mind but can be used with other fastcgi implementation...

***-How do I write and compile a simple FastCGI C++ Program using g++?***

this the link you refer is talking about C kit more than C++ kit in fact... but in C++ you can use natively c code. 

all are explain in this part : https://fastcgi-archives.github.io/FastCGI_Developers_Kit_FastCGI.html#S3.1

for c++ object api use : http://cgi.sourceforge.net/

***-How do I write html, css, javascript to an .html web document?***

fastcgi is not related directly to css/javascript nor html... they generate content to stdout to the web  serveur... and you can generate what you whant... generally fastcgi are used to generate dynamic page (html or for now json for exemple)...

***-How do I read http GET and POST content to and from variables involved in GET and POST actions from an html (http) web form action?***

is a cgi and all header http are passed by environement variable...
and post content by the stdin...

**Comment by mcarbonneaux** [comment]
http://chriswu.me/blog/writing-hello-world-in-fcgi-with-c-plus-plus/

**Comment by mcarbonneaux** [comment]
you have example in example directory  : 
https://github.com/FastCGI-Archives/fcgi2/blob/master/examples/echo-cpp.cpp
read the make file to see how to compile.

**Comment by PowerUser1234** [comment]
-Is the version of FastCGI from the website 32 bit or 64 bit?  Can it be recompiled directly and easily
with a g++ -w64 compilation switch?

-Is there a 64 bit Apache plugin or module that is compiled somewhere on the public internet that can be used?  If not, is it possible for someone to compile and post one, kindly?

**Comment by mcarbonneaux** [comment]
***-Is the version of FastCGI from the website 32 bit or 64 bit? Can it be recompiled directly and easily
with a g++ -w64 compilation switch?***

i down know if it's compile in 64bit... but it's compile on linux 64bit with gcc/g++ (all standard linux distribution that include the fcgi sdk had compiled it in 64bit in my know...)...

generaly the fcgi library is included in majority of linux distribution (libfcgi in debian/ubuntu and fcgi in centos epel) and all are compiled in general in 64bit without problem...

***-Is there a 64 bit Apache plugin or module that is compiled somewhere on the public internet that can be used? If not, is it possible for someone to compile and post one, kindly?***

see in my response below... is already embeded in apache... the apache module that support it is mod_proxy_fcgi... and all standard linux distribution that have apache package include the mod_proxy_fastcgi also...

**Comment by PowerUser1234** [comment]
-Does the module for fast cgi come by default with the latest 64 bit version of Apache?  I'm sorry to repeat a question, it's simply that you English is subtly unclear.

?

**Comment by mcarbonneaux** [comment]
has i said below... 

***-How do I install and configure FastCGI for Apache, if it isn't enables easily or already done so in Apache, by default?***

Apache from 2.4 version natively ***includes fastcgi*** support...
and all distribution that had apache package had mod_proxy_fcgi also...

- see on page of apache documentation : https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html

is oriented with php fastcgi in mind but can be used with other fastcgi implementation...

and apache can be compiled in 64bit or 32bit for long time and include the fact that mod_proxy_fcgi also compile because is part of apache...
