### ISSUE TITLE
autoreconf: /usr/bin/autoconf failed with exit status: 1

### ISSUE THREAD

**Issue by HhTtLllL** [FastCGI-Archives/fcgi2#39]
Hello, I am using ubuntu 18.04, but when I use the command ./autogen.sh.

The results are as follows:

configure.ac:17: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

**Comment by yxdming** [comment]
I got the same error on SuSE 11.3. 
I will appriciate it so much if somone help us to solve this issue.

**Comment by mcarbonneaux** [comment]
you installed libtool package ?

**Comment by iosx** [comment]
I got the same error on Ubuntu 16.04.7 LTS (GNU/Linux 4.4.0-186-generic x86_64).
Libtool is installed.

**Comment by mcarbonneaux** [comment]
This error occur only when autoconf not found libtool m4 file... Generally when libtool is not installed or bad installed...

If you installed manually libtool (not with apt get) if possible that you not installed in the place where autoconf m4 are...

Use only libtool and autoconf from the distribution.

```
apt install gcc make m4 autoconf automake libtool
```
