### ISSUE TITLE
Memory leak in ProcessManagementRecord()

### ISSUE THREAD

**Issue by Thomas-Brandt** [FastCGI-Archives/fcgi2#42]
Hi,

ppisar figured out a memory leak and fixed it at: 
https://github.com/perl-catalyst/FCGI/pull/4

**paramsPtr variable was always allocated but freed only if type was
FCGI_GET_VALUES. In other cases the variable leaked. 
This patch fixes it.**

I modified the patch to the current HEAD.
Unfortunatly I'm not able to create a pull request due to not 
allowed to push it to the repo.
Please finde the patch below.
**All credits to: ppisar.**

[ProcessManagementRecord_leak_fix.txt](https://github.com/FastCGI-Archives/fcgi2/files/4328649/ProcessManagementRecord_leak_fix.txt)

**Comment by Thomas-Brandt** [comment]
I forked the repo and created a pull request.
Issue can be closed.

**Comment by LeSpocky** [comment]
This was hand

> I forked the repo and created a pull request.
> Issue can be closed.

The PR is #43 and that was already merged with ca92b995d836c84e0433c1550c82dbdc98e5237c, right?

**Comment by Thomas-Brandt** [comment]
Yes  the PR contains the fix
