### ISSUE TITLE
Remove dependency to deprecated libnsl

### ISSUE THREAD

**Issue by Thomas-Brandt** [FastCGI-Archives/fcgi2#45]
Beginning with GNU C library in version 2.26 libnsl is no longer installed by default. 
Please remove the dependency to deprecated libnsl. 
It seems that the only reason for that dependency is usage of the function “gethostbyname”. 
The usually used replacement for this function is “getaddrinfo”.

**Comment by mcarbonneaux** [comment]
you can push a pull request to do that ?

**Comment by Thomas-Brandt** [comment]
Currently we do not use this part of functionality. 
We found a workaround for our use case (which is just removing the function calls completely) to get this package compiled.
Unfortunately we cannot provide at this moment a working implementation for all users of this library.
