### ISSUE TITLE
Branch / Versioning

### ISSUE THREAD

**Issue by atari83** [FastCGI-Archives/fcgi2#46]
Hello there and thanks for beautiful job :)
So, I've used FastCGI library in one of my projects before and I tend to make some updates to it, then I noticed you've forked the project and made some bug-fixes.

So, my question is if current code-base is ready to go released or branched any soon ? Or is safe to ship my code with existing 'master' code ?

**Comment by mcarbonneaux** [comment]
This is an archive, I accept no major evolution, only bug fix. The master contain for the moment only bug fix vs original.
