### ISSUE TITLE
Difference between libfcgi and libscgi

### ISSUE THREAD

**Issue by ghost** [FastCGI-Archives/fcgi2#52]
Hello!
What is the difference between them? Does libfcgi provide better performance than libscgi server?
Thank you.

**Comment by mcarbonneaux** [comment]
i dont know but... scgi has been developped after fastcgi... 

fastcgi (like http2) are binary protocol and more bandwith optimized, and can be multiplexed...

scgi are text protocol (like http1) and cannot be multiplexed like http2 and fastcgi...

scgi has been developped on the ombrela of python... and more integreted with python... 

fastcgi a more language agnostic...

https://python.ca/scgi/protocol.txt
