### ISSUE TITLE
Is Yandex libfcgi patch applied to current repository?

### ISSUE THREAD

**Issue by ghost** [FastCGI-Archives/fcgi2#54]
Hi, guys!
I found repository [libfcgi](https://github.com/toshic/libfcgi) and description here [launchpad](https://bugs.launchpad.net/ubuntu/+source/libfcgi/+bug/933417)
Is mentioned patch applied to fcgi2 repository? Thank you.

**Comment by mcarbonneaux** [comment]
on launchpad is the ubuntu package repository...
her if a fork of the original project site who a re now down... to maintaine all the original material of github.
the yandex patch are unknow  for me, if you whant to create a pull request i while include it!

**Comment by tehnick** [comment]
@mcarbonneaux
I have already pushed all patches from Debian packages to upstream. You may close this issue. See 5c15a7bb5260bc83715090c9fd386d704c139671

**Comment by tehnick** [comment]
@mcarbonneaux BTW you could add me to members of FastCGI-Archives project. ;-)
