### ISSUE TITLE
How to create a fastCGI in Pascal ?

### ISSUE THREAD

**Issue by Mat-Hac** [FastCGI-Archives/fcgi2#55]
Hello,

I want to adapt ExtPascal to fCGI2.

But the doc is not enough. Can you upgrade the doc we to use not only in C ? Can you upgrade the doc with the new examples ?

**Comment by Mat-Hac** [comment]
Can you create a doc for nginx or apache ?

**Comment by mcarbonneaux** [comment]
i'm not maintenaing extpascal but archives of fastcgi.com.

if you speak about this project : https://github.com/farshadmohajeri/extpascal

i think you use the documentation of the project in : https://github.com/farshadmohajeri/extpascal/tree/master/docs

or https://www.freepascal.org/~michael/articles/extpascal/extpascal.pdf

in fact extpascal not use fcgi2, seem to support natively fastcgi protocol.

**Comment by Mat-Hac** [comment]
I want to use your fascgi project in pascal.
I know how to link to your project.
But i do not find where tu put cgi-fcgi exe.

**Comment by mcarbonneaux** [comment]
[extpascal has native fastcgi in document](https://www.freepascal.org/~michael/articles/extpascal/extpascal.pdf) i sent that not need cgi to fastcgi convertion ([cgi-fcgi](https://github.com/FastCGI-Archives/fcgi2/blob/master/doc/cgi-fcgi.1)).

cgi-fcgi is to convert old cgi mode (using fork) program to fastcgi is not the prefered and performante solution to do fastcgi, prefer native fastcgi mode in process prefork or pool of thread.

php for exemple now start in prefork mode with php_fpm.
lighttpd has a prefork fcgi spawn daemon for cgi compatible program (more performante that cgi-fcgi): https://redmine.lighttpd.net/projects/spawn-fcgi/wiki 
apache and with [the old mod_fastcgi](https://github.com/FastCGI-Archives/mod_fastcgi) support apache to fastcgi.
apache now has fastcgi integrated [mod_fastcgi](https://httpd.apache.org/docs/2.4/fr/mod/mod_proxy_fcgi.html).

nginx also has integrated fastcgi support : 
- http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html
- https://www.nginx.com/resources/wiki/start/topics/examples/fastcgiexample/

you need to start your process standalone in fastcgi mode (fastcgi native or with cgi-fcgi), and configure nginx/apache to talk with it in fastcgi protocol (with tcp or unix socket) with there respective fastcgi module.
