### ISSUE TITLE
Could you recommend anything to get files from multipart/form-data?

### ISSUE THREAD

**Issue by ghost** [FastCGI-Archives/fcgi2#57]
Hi!
I am sending video file via FormData() using XmlHttpRequest(). Could you provide some details on how to obtain file back on the server side in C, please?
Thank you.

**Comment by ghost** [comment]
Maybe this library has underlying mechanism for that purpose?

**Comment by ghost** [comment]
And could you tell how to extract multipart/form-data data for parsing in C?

**Comment by mcarbonneaux** [comment]
> in

i don't know ! i've not used in this way...

**Comment by mcarbonneaux** [comment]
but in googling: https://stackoverflow.com/questions/2265038/is-there-a-lightweight-multipart-form-data-parser-in-c-or-c
