### ISSUE TITLE
Defects found in static analysis 

### ISSUE THREAD

**Issue by alisha22** [FastCGI-Archives/fcgi2#7]
I am using libfcgi-2.4.0 armhf version in my application. Which is available here https://packages.ubuntu.com/trusty/armhf/libfcgi-dev

We run Coverity Scan on code and we have found the following defects:

1. File fcgiapp.c
    line 597 : p = (char *)memchr(charPtrArg, '\0', precision);
    defect : Out-of-bounds access. Access of memory not owned by this buffer may cause crashes or incorrect computations. Overrunning buffer pointed to by charPtrArg of 7 bytes by passing it to  function which accesses it at byte offset 999998 using argument precision (which evaluates to 999999).

2. File fcgiapp.c
     line 1468 :             *(strchr(name, '=')) = '\0';
     defect : Dereference null return value. If the function actually returns a null value, a null pointer
              dereference will occur. Dereferencing strchr(name, 61), which is known to be NULL.

3. File fcgio.cpp
    line 164 and 172 :     if (n > INT_MAX) return 0;
    defect : Operands don't affect result. The expression's value does not depend on the operands; often,
              this represents an inadvertent logic error. result_independent_of_operands: n > 2147483647 is
              always false regardless of the values of its operands. This occurs as the logical operand of if

Please let me know if these issues will be getting fixed in coming versions.

**Comment by mcarbonneaux** [comment]
Push a merge request.

**Comment by tehnick** [comment]
`2` and `3` should be fixed in #15
